# Generated by Django 5.1.6 on 2025-07-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_player_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
    ]
