# Generated by Django 5.1.6 on 2025-08-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_opponent_match_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_complete',
            field=models.BooleanField(default=False),
        ),
    ]
