# Generated by Django 5.1.6 on 2025-08-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_match_match_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age_bracket', models.CharField(choices=[('U8', 'Under 8'), ('U9', 'Under 9')], max_length=10)),
                ('category', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIXED', 'Mixed')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='age_group',
            field=models.CharField(default='Under 8', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(default='Female', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.league'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Opponent',
        ),
    ]
