# Generated by Django 5.1.6 on 2025-08-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_league_alter_match_opponent_team_age_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='age_bracket',
            new_name='age_group',
        ),
    ]
