# Generated by Django 5.1.6 on 2025-08-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_age_bracket_league_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='age_group',
            field=models.CharField(choices=[('U8', 'Under 8'), ('U9', 'Under 9')], max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIXED', 'Mixed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.league'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, to='teams.player'),
        ),
    ]
