# Generated by Django 5.1.6 on 2025-08-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_team_age_group_alter_team_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
