# Generated by Django 5.1.6 on 2025-08-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_team_read_only_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='read_only_users',
        ),
    ]
