# Generated by Django 5.1.6 on 2025-08-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_player_user_alter_team_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
